### ISSUE TITLE
error

### ISSUE THREAD

**Issue by imSunnyk** [niraj-khatiwada/Learning-Management-System#3]
I installed requirements successfully..
but when I executed commands as

python manage.py makemigrations
it showed error
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sandeep/Finalized Project/PROJECTS/LMS/lms/settings.py", line 26, in <module>
    SECRET_KEY = config('SECRET_KEY')
  File "/home/sandeep/.local/lib/python3.8/site-packages/decouple.py", line 199, in __call__
    return self.config(*args, **kwargs)
  File "/home/sandeep/.local/lib/python3.8/site-packages/decouple.py", line 83, in __call__
    return self.get(*args, **kwargs)
  File "/home/sandeep/.local/lib/python3.8/site-packages/decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.

what to do?

**Comment by codydematth** [comment]
Oh Sorry, have you been able to solve the Error?
